# Глава 10. Обработка исключений

**Исключение** - ошибка, возникающая во время выполнения программы.
После возникновения ошибки исполняющей системой Java или прикладным кодом создаётся объект исключения, исключение
генерируется (прерывая выполнение кода), затем перехватывается обработчиком исключений и обрабатывается.
Если в прикладном коде обработчик исключения отсутствует, то исключение перехватывается стандартным обработчиком, 
предоставляемым исполняющей системой Java. Стандартный обработчик выводит строку с описанием исключения и трассировкой 
стека (последовательностью вызовов методов с местом возникновения ошибки) и прерывает выполнение программы.

**Ключевые слова** для управления обработкой исключений:
* **try** - начало блока кода, который потенциально может привести к ошибке;
* **catch** - начало блока кода, предназначенного для перехвата и обработки исключений;
* **throw** - служит для генерации исключений;
* **throws** - прописывается в сигнатуре метода и обозначает, что метод потенциально может выбросить исключение 
  с указанным типом;
* **finally** - начало необязательного блока кода (после последнего блока catch), который выполнится в любом случае,
  независимо от того, возникнет исключение или нет.

```
try {
    // блок кода, в котором отслеживаются исключения
} catch (тип_исключения_1 объект_исключения_1) {
    // обработчик исключений типа тип_исключения_1
} catch (тип_исключения_2 объект_исключения_2) {
    // обработчик исключений типа тип_исключения_2
} catch (тип_исключения_n объект_исключения_n) {
    // обработчик исключений типа тип_исключения_n
} finally {
    // блок кода, который выполнится после завершения выполнения блока try
    // в любом случае (возникло исключение или нет)
} 
```

Возможно применять несколько операторов catch, вложенные операторы try.
Когда управление передаётся блоку кода оператора try, то контекст соответствующего исключения размещается в стеке.

## Оператор throw

Оператор **throw** предназначен для генерации исключения.
```
throw генерируемый_экземпляр;   // объект класса Throwable или производного от него подкласса
```
Получить генерируемый экземпляр класса можно двумя способами:
* указав соответствующий параметр в операторе **catch**;
* создав объект с помощью оператора **new**.

## Оператор throws

Если выполнение **метода** может сгенерировать исключение, которое он сам не обрабатывает, то метод должен быть
объявлен с оператором **throws**. Этим обработка исключения передаётся на уровень выше по коду. За оператором throws
перечисляются типы исключений, которые может сгенерировать метод. Это обязательно для всех исключений,
кроме исключений классов Error и RuntimeException и их подклассов.
```
тип имя_метода(список_параметров) throws класс_исключения_1, класс_исключения_2, класс_исключения_n
{
    // тело метода
}
```

## Оператор finally

Оператор **finally** образует блок кода, который будет выполнен независимо от того сгенерировано исключение или нет.

## Иерархия классов исключений

* **Throwable** (java.lang.Throwable) - вершина иерархии классов исключений;
  * **Exception** - исключения, которые перехватывает прикладной код. От этого класса можно создавать (наследовать) свои
    собственные подклассы исключений;
    * **RuntimeException** - подклассы этого класса - встроенные в Java исключения, автоматически определены в прикладном 
      коде для таких ошибок, как деление на нуль (ArithmeticException), ошибочная индексация массивов
      (ArrayIndexOutOfBoundsException) и других ошибок программирования;
    * **Другие исключения** непредвиденного стечения обстоятельств, возникающих при выполнении вполне корректных программ,
      например, ошибок ввода-вывода (IOException), SQLException, ReflectiveOperationException;
  * **Error** - исключения в исполняющей системе Java (JRE), которые согласно спецификации Java не следует обрабатывать
      в прикладном коде, например, переполнение стека (StackOverflowError).

**Два типа исключений**:

* **Проверяемые** (checked) - исключения, которые проверяются перед компиляцией программы.
  Они должны быть обработаны в блоке catch или описываться в сигнатуре метода с помощью throws.
  Исключение в любом случае нужно будет перехватить и обработать, иначе программа не скомпилируется.
  Наследуются от класса Exception (кроме RuntimeException и его подклассов), например, IOException, SQLException.
  
* **Непроверяемые** (unchecked) - исключения, которые нельзя проверить до компиляции.
  Их можно не обрабатывать и не описывать в сигнатуре метода (но возможно).
    * ошибки - класс Error и его подклассы (например, StackOverflowError, OutOfMemoryError);
    * исключения времени выполнения - RuntimeException и его подклассы (например, NullPointerException,
      IndexOutOfBoundsException, ArithmeticException).

**Проверяемые** исключения, определённые в пакете `java.lang`

| Исключение                      | Описание                                                                           |
| ------------------------------- | ---------------------------------------------------------------------------------- |
| ClassNotFoundException          | Класс не найден                                                                    |
| CloneNotSupportedException      | Попытка клонировать объект из класса, не реализующего интерфейс Cloneable          |
| IllegalAccessException          | Доступ к классу не разрешен                                                        |
| InstantiationException          | Попытка создать объект абстрактного класса или интерфейса                          |
| InterruptedException            | Один поток исполнения прерван другим потоком                                       |
| NoSuchFieldException            | Запрашиваемое поле не существует                                                   |
| NoSuchMethodException           | Запрашиваемый метод не существует                                                  |
| ReflectiveOperationException    | Суперкласс исключений, связанных с рефлексией                                      |

**Непроверяемые** исключения (подклассы RuntimeException), определённые в пакете `java.lang`

| Исключение                      | Описание                                                                           |
| ------------------------------- | ---------------------------------------------------------------------------------- |
| ArithmeticException             | Арифметическая ошибка (например, деление на нуль)                                  |
| ArrayIndexOutOfBoundsException  | Выход индекса за пределы массива                                                   |
| ArrayStoreException             | Присваивание элементу массива объекта несовместимого типа                          |
| ClassCastException              | Неверное приведение типов                                                          |
| EnumConstantNotPresentException | Попытка воспользоваться неопределенным значением перечисления                      |
| IllegalArgumentException        | Употребление недопустимого аргумента при вызове метода                             |
| IllegalMonitorStateException    | Недопустимая контрольная операция (например, ожидание незаблокированного потока исполнения) |
| IllegalStateException           | Неверное состояние среды или приложения                                            |
| IllegalThreadStateException     | Несовместимость запрашиваемой операции с текушим состоянием потока исполнения      |
| IndexOutOfBoundsException       | Выход индекса некоторого типа за допустимые пределы                                |
| NegativeArraySizeException      | Создание массива отрицательного размера                                            |
| NullPointerException            | Неверное использование пустой ссылки                                               |
| NumberFormatException           | Неверное преобразование символьной строки в числовой формат                        |
| SecurityException               | Попытка нарушения безопасности                                                     |
| StringIndexOutOfBounds          | Попытка индексации за пределами символьной строки                                  |
| TypeNotPresentException         | Тип не найден                                                                      |
| UnsupportedOperationException   | Обнаружена неподдерживаемая операция                                               |

## Создание собственных подклассов исключений

Достаточно определить класс, производный от класса  Exception:
```
class MyException extends Exception {
}
```

## Цепочки исключений

**Цепочки исключений** - это средство (добавленное в JDK 1.4), позволяющее связывать одно исключение с другим для
описания в последнем исключении причину возникновения первого.
Для реализации цепочки исключений в класс Throwable введены два конструктора и два метода:
```
Тhrowable (Тhrowable причина_исключения);
Тhrowable (String сообщение, Тhrowable причина_исключения);
Тhrowable getCause();                               // возвращает исключение (или null), вызывающее текущее исключение
Тhrowable initCause(Тhrowable причина_исключения);  // связывает причину_исключения с вызывающим исключением
                                                    // и возвращает ссылку на исключение; можно вызвать только один раз
```

## Новые средства для обработки исключений

В версии JDK 7 добавлены 3 новых средства для обработки исключений:

* **Расширенная форма оператора try (try с ресурсами)** - автоматическое управление ресурсами - 
  для автоматического освобождения ресурсов (потоков ввода-вывода, файлов, др.), когда они становятся больше не нужны. 
  Может также включать в себя операторы catch, finally. Оператор try с ресурсами применяется только с теми ресурсами, 
  которые реализуют интерфейс java.lang.AutoCloseable (метод close()).
```
try (спецификация_ресурса_1;        // объявление и инициализация ресурсов
     спецификация_ресурса_n) {
    // использование ресурсов
}
```
  У оператора _try с ресурсами_ есть особенность: когда выполняется блок оператора try, есть вероятность того, 
  что исключение, возникающее в блоке оператора try, приведет к другому исключению, которое произойдет в тот момент,
  когда ресурс закрывается в блоке оператора finally. Если это "обычный" оператор try, то первоначальное исключение 
  теряется, будучи вытесненным вторым исключением. А если используется оператор try с ресурсами, то второе исключение
  подавляется, но не теряется. Вместо этого оно добавляется в список подавленных исключений, связанных с первым исключением.
  Доступ к списку подавленных исключений может быть получен с помощью метода  getSuppressed(), определенного в классе Throwable.

* **Многократный перехват исключений** - позволяет указывать в одном операторе catch несколько классов исключений.
  Используется логическая операция ИЛИ (|). Каждый параметр многократного перехвата неявно считается завершенным (final),
  т.е. ему нельзя присваивать новое значение в блоке оператора catch.
```
try {
    // генерация исключений
} catch (класс_исключения_1 | класс_исключения_2 | класс_исключения_n ex) {
    // обработка исключения из указанных классов
}
```

* **Окончательное повторное генерирование исключений** (более точное повторное генерирование исключений с улучшенной 
  проверкой типов). В версии JDK 7 компилятор выполняет более точный анализ повторных исключений, чем предыдущие версии.
  Это позволяет указать более конкретные типы исключений в операторе throws объявления метода.
  
  Например, есть два класса исключений (подклассы Exception) - FirstException и SecondException.
  Блок try может вызывать либо FirstException, либо SecondException. Предположим, что необходимо указать эти типы
  исключений в throws объявления метода rethrowException().
  
  **До JDK 7** этого нельзя сделать.
  Поскольку параметр ex исключения в catch (Exception ex) является классом Exception, а в блоке кода catch повторно
  выбрасывается исключения ex, то в объявлении метода в throws можно указать только тип исключения Exception.
  
  **Начиная с JDK 7** в объявлении метода в throws стало возможным указать типы исключений FirstException и SecondException.
  Компилятор JDK 7 может определить, что исключение, вызванное выражением throw, должно быть получено из блока try, 
  и единственными исключениями, сгенерированными в этом блоке, могут быть FirstException и SecondException.
  Несмотря на то, что параметр исключения ex в catch (Exception ex) является типом Exception, 
  компилятор может определить, что он является экземпляром FirstException или SecondException.

```
static class FirstException extends Exception { }
static class SecondException extends Exception { }

// До JDK 7

public void rethrowException(String exceptionName) throws Exception {
    try {
        if (exceptionName.equals("First")) {
            throw new FirstException();
        } else {
            throw new SecondException();
        }
    } catch (Exception ex) {
        throw ex;
    }
}

// Начиная с JDK 7

public void rethrowException(String exceptionName) throws FirstException, SecondException {
    try {
        // ...
    } catch (Exception ex) {
        throw ex;
    }
}
```
